### ISSUE TITLE
DSA in C

### ISSUE THREAD

**Issue by droidmaximus** [iamsidofficial/c-programs-for-college-students#5]
Hello, I would like to contribute to your repo by adding common dsa algorithms and data structures. Please tag this issue under hacktoberfest-accepted and hacktoberfest. Thank you.

**Comment by iamsidofficial** [comment]
This repo has the topic 'hacktoberfest' added to it, so there is no need to manually add 'hacktoberfest-accepted'. However if you want me to add tags, I will add the same once you make a valid pull request. Good Luck Contributing!
